version: "3.9"

services:
  node-1:
    build: ./node
    environment:
      - NODE_NAME=node-1
    ports:
      - "8101:8080"

  node-2:
    build: ./node
    environment:
      - NODE_NAME=node-2
    ports:
      - "8102:8080"
