version: "3.9"

services:
  node-1:
    build: ./node
    environment:
      - NODE_NAME=node-1
    ports:
      - "8101:8080"

  node-2:
    build: ./node
    environment:
      - NODE_NAME=node-2
    ports:
      - "8102:8080"
  cam-service:
    build: ./cam
    ports:
      - "9000:9000"
  cag-gateway:
    build: ./cag
    ports:
      - "8000:8000"
    depends_on:
      - cam-service
      - node-1
      - node-2
